import type { Metadata } from "next";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "Livraria Moraes",
    description: "Generated by Tiago Moraes",
};

export default function GeneralLayout({
        children,
}: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <div className="min-h-screen">
            <Header />
            {children}
        </div>
    );
};